env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
  - testing-library
rules:
  "testing-library/await-async-query": "error"
  "testing-library/no-await-sync-query": "error"
  "testing-library/no-debugging-utils": "warn"
  "testing-library/no-dom-import": "off"
